# Generated by Django 5.0.4 on 2024-04-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choice_test",
            new_name="choice_text",
        ),
    ]
